package com.omnia.ecommerce.dao;

import com.omnia.ecommerce.entity.Product;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestParam;

@CrossOrigin("http://localhost:4200")
@RepositoryRestResource(collectionResourceRel = "Products",path = "Products" )

public interface ProductRepository extends JpaRepository<Product,Long>{
//  all the code is generated by the annotations


    Page<Product> findByCategoryId(@RequestParam("id") Long id, Pageable pageable);
}
